api_platform:
    title: "Api Platform"

    doctrine:
        enabled: false

    mapping:
        paths:
            - '%kernel.project_dir%/src/Admin/Infrastructure/Platform/Resource/Admin.resource.xml'

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: "Authorization"
                type: header

    exception_to_status:
        App\Common\Domain\Assert\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST

        DomainException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        App\Common\Domain\Specification\SpecificationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        Symfony\Component\Messenger\Exception\HandlerFailedException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
