api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Admin/Infrastructure/API/Resource/Admin.xml'

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
