image: makeitlv/php:8.1.5

stages:
    - build
    - test
    - deploy

variables:
    DOCKER_DRIVER: overlay2

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .env
        - composer.phar
        - vendor/
        - var/cache
        - .phpunit.result.cache

build-php:
    stage: build
    script:
        - curl --show-error --silent "https://getcomposer.org/installer" | php
        - php composer.phar install --ignore-platform-reqs --no-ansi --no-interaction --no-scripts
        - php composer.phar dump-autoload --optimize --classmap-authoritative
        - php composer.phar check-platform-reqs

codestyle:
    stage: test
    script:
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=dev
        - php -d memory_limit=-1 ./vendor/bin/phpcs --standard=phpcs.xml
        - php -d memory_limit=-1 ./vendor/bin/phpcpd --fuzzy src/ config/
        - php -d memory_limit=-1 ./vendor/bin/psalm --no-progress=true --output-format=text -m
        - php -d memory_limit=-1 ./vendor/bin/deptrac analyse --config-file=deptrac.yaml

test:
    stage: test
    services:
        - postgres:13-alpine
    variables:
        POSTGRES_DB: app_test
        POSTGRES_USER: symfony
        POSTGRES_PASSWORD: ChangeMe
        POSTGRES_HOST: postgres
        POSTGRES_PORT: '5432'
    before_script:
        - apk add --no-cache --virtual .pgsql-deps postgresql-dev
        - docker-php-ext-install -j$(nproc) pdo_pgsql
        - apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5
        - apk del .pgsql-deps
    script:
        - php -d memory_limit=-1 ./bin/console lexik:jwt:generate-keypair --env=test --skip-if-exists --quiet
        - php -d memory_limit=-1 ./bin/console doctrine:database:create --env=test --if-not-exists
        - php -d memory_limit=-1 ./bin/console doctrine:schema:drop --env=test --force
        - php -d memory_limit=-1 ./bin/console doctrine:schema:create --env=test
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=test
        - php -d memory_limit=-1 ./bin/phpunit
