api:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api
        permanent: true

api_login_check:
    path: /api/admin/auth/login

api_refresh_token:
    path: /api/admin/auth/refresh

kernel:
    resource: ../src/Kernel.php
    type: annotation
