# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(APP_DOMAIN): 'localhost'
    domain: '%env(string:APP_DOMAIN)%'
    
    sender: 'info@%domain%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Common\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Common\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Common\Domain\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

        App\Common\Infrastructure\EventSubscriber\DomainEventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Common\Infrastructure\Bus\Command\CommandBus:
        arguments:
            $commandBus: '@command.bus'

    App\Common\Infrastructure\Bus\Query\QueryBus:
        arguments:
            $messageBus: '@query.bus'

    App\Common\Infrastructure\Bus\Event\EventBus:
        arguments:
            $eventBus: '@event.bus'

    admin.create.specification:
        class: App\Common\Domain\Specification\SpecificationList
        arguments:
            $specifications:
                - '@App\Admin\Domain\Specification\UniqueEmailSpecificationInterface'

    App\Admin\Application\UseCase\Command\Create\CreateHandler:
        arguments:
            $specification: '@admin.create.specification'

    App\Admin\Application\UseCase\Command\Register\RegisterHandler:
        arguments:
            $specification: '@admin.create.specification'

    App\Admin\Application\UseCase\Command\Update\UpdateHandler:
        arguments:
            $specification: '@admin.create.specification'

    App\Common\Infrastructure\Platform\Serializer\ApiNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'

    'app.common.infrastructure.platform.serializer.api.normalizer':
        class: 'App\Common\Infrastructure\Platform\Serializer\ApiNormalizer'
        decorates: 'api_platform.serializer.normalizer.item'
        
    App\Security\Infrastructure\Platform\Decorator\SwaggerAuthDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]
